config/routes.rb
Rails.application.routes.draw do

  resources :tipo_contenidos

  get 'home/index'
  get 'home/contacto'

  resources :entrada_blogs do
      resources :comentarios
  end

  resources :usuarios

   root :to => 'home#index'

  get 'foto' => 'entrada_blogs#foto'
  get 'mates' => 'entrada_blogs#mates'
  get 'editablog' => 'entrada_blogs#editablog'

resources :sitemaps, :only => :index
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

end

app/models/tipo_contenido.rb
class TipoContenido < ActiveRecord::Base

	belongs_to :entrada_blogs


end

app/controllers/tipo_contenidos_controller.rb
class TipoContenidosController < ApplicationController
  before_action :set_tipo_contenido, only: [:show, :edit, :update, :destroy]

  # GET /tipo_contenidos
  # GET /tipo_contenidos.json
  def index
    @tipo_contenidos = TipoContenido.all
  end

  # GET /tipo_contenidos/1
  # GET /tipo_contenidos/1.json
  def show
  end

  # GET /tipo_contenidos/new
  def new
    @tipo_contenido = TipoContenido.new
  end

  # GET /tipo_contenidos/1/edit
  def edit
  end

  # POST /tipo_contenidos
  # POST /tipo_contenidos.json
  def create
    @tipo_contenido = TipoContenido.new(tipo_contenido_params)

    respond_to do |format|
      if @tipo_contenido.save
        format.html { redirect_to @tipo_contenido, notice: 'Tipo contenido was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_contenido }
      else
        format.html { render :new }
        format.json { render json: @tipo_contenido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_contenidos/1
  # PATCH/PUT /tipo_contenidos/1.json
  def update
    respond_to do |format|
      if @tipo_contenido.update(tipo_contenido_params)
        format.html { redirect_to @tipo_contenido, notice: 'Tipo contenido was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_contenido }
      else
        format.html { render :edit }
        format.json { render json: @tipo_contenido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_contenidos/1
  # DELETE /tipo_contenidos/1.json
  def destroy
    @tipo_contenido.destroy
    respond_to do |format|
      format.html { redirect_to tipo_contenidos_url, notice: 'Tipo contenido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_contenido
      @tipo_contenido = TipoContenido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_contenido_params
      params.require(:tipo_contenido).permit(:astrofoto, :metematica, :otro1, :otro2, :otrotxt)
    end
end

app/helpers/tipo_contenidos_helper.rb
module TipoContenidosHelper
end

app/views/tipo_contenidos/_form.html.erb
<%= form_for(@tipo_contenido) do |f| %>
  <% if @tipo_contenido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_contenido.errors.count, "error") %> prohibited this tipo_contenido from being saved:</h2>

      <ul>
      <% @tipo_contenido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :astrofoto %><br>
    <%= f.check_box :astrofoto %>
  </div>
  <div class="field">
    <%= f.label :metematica %><br>
    <%= f.check_box :metematica %>
  </div>
  <div class="field">
    <%= f.label :otro1 %><br>
    <%= f.check_box :otro1 %>
  </div>
  <div class="field">
    <%= f.label :otro2 %><br>
    <%= f.check_box :otro2 %>
  </div>
  <div class="field">
    <%= f.label :otrotxt %><br>
    <%= f.text_field :otrotxt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_contenidos/edit.html.erb
<h1>Editing Tipo Contenido</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_contenido %> |
<%= link_to 'Back', tipo_contenidos_path %>

app/views/tipo_contenidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipo Contenidos</h1>

<table>
  <thead>
    <tr>
      <th>Astrofoto</th>
      <th>Metematica</th>
      <th>Otro1</th>
      <th>Otro2</th>
      <th>Otrotxt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_contenidos.each do |tipo_contenido| %>
      <tr>
        <td><%= tipo_contenido.astrofoto %></td>
        <td><%= tipo_contenido.metematica %></td>
        <td><%= tipo_contenido.otro1 %></td>
        <td><%= tipo_contenido.otro2 %></td>
        <td><%= tipo_contenido.otrotxt %></td>
        <td><%= link_to 'Show', tipo_contenido %></td>
        <td><%= link_to 'Edit', edit_tipo_contenido_path(tipo_contenido) %></td>
        <td><%= link_to 'Destroy', tipo_contenido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo contenido', new_tipo_contenido_path %>

app/views/tipo_contenidos/new.html.erb
<h1>New Tipo Contenido</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_contenidos_path %>

app/views/tipo_contenidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Astrofoto:</strong>
  <%= @tipo_contenido.astrofoto %>
</p>

<p>
  <strong>Metematica:</strong>
  <%= @tipo_contenido.metematica %>
</p>

<p>
  <strong>Otro1:</strong>
  <%= @tipo_contenido.otro1 %>
</p>

<p>
  <strong>Otro2:</strong>
  <%= @tipo_contenido.otro2 %>
</p>

<p>
  <strong>Otrotxt:</strong>
  <%= @tipo_contenido.otrotxt %>
</p>

<%= link_to 'Edit', edit_tipo_contenido_path(@tipo_contenido) %> |
<%= link_to 'Back', tipo_contenidos_path %>