config/routes.rb
Rails.application.routes.draw do

  resources :tipo_contenidos

  get 'home/index'
  get 'home/contacto'

  resources :entrada_blogs do
      resources :comentarios
  end

  resources :usuarios

   root :to => 'home#index'

  get 'foto' => 'entrada_blogs#foto'
  get 'mates' => 'entrada_blogs#mates'
  get 'editablog' => 'entrada_blogs#editablog'

resources :sitemaps, :only => :index
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    apply_simple_captcha
    validates :Nombre, :email, presence: true
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :email, uniqueness: true
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  



  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  def new
    @usuario = Usuario.new
  end
  
def create
    @usuario = Usuario.new(usuario_params)


    respond_to do |format|
      #se guarda el usuario si el captcha está escrito correctamente.
      if @usuario.save_with_captcha

        #se envía el correo de confirmación de la creación de usuario.
        MailUsuario.email_bienvenida(@usuario).deliver_now


        format.html { redirect_to :back, notice: 'Suscripción creada correctamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { redirect_to :back, notice: 'Error en la suscripción. Comprueba que has escrito tu nombre, email o captcha correctamente.' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end


  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new


  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:Nombre, :email, :codigo, :captcha, :captcha_key)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="button">
    <%= f.radio_button :codigo, "foto" %>
    <%= f.label :codigo, 'Solo Fotografías' %>
  </div>
  <div class="button">
    <%= f.radio_button :codigo, "mates" %>
    <%= f.label :codigo, 'Solo matemáticas' %>
  </div>
  <div class="button">
    <%= f.radio_button :codigo, "todo", checked: true %>
    <%= f.label :codigo, 'Todas las actualizaciones' %>
  </div>

<%= show_simple_captcha(:object=>"usuario") %>

  <div class="actions">
    <%= f.submit "Suscribirme" %>
  </div>
  
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index33.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Codigo</th>
      <th>Solofotos</th>
      <th>Solomates</th>
      <th>Completo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.Nombre %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.codigo %></td>
        <td><%= usuario.solofotos %></td>
        <td><%= usuario.solomates %></td>
        <td><%= usuario.completo %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Suscribirme</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.Nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @usuario.codigo %>
</p>

<p>
  <strong>Solofotos:</strong>
  <%= @usuario.solofotos %>
</p>

<p>
  <strong>Solomates:</strong>
  <%= @usuario.solomates %>
</p>

<p>
  <strong>Completo:</strong>
  <%= @usuario.completo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>