config/routes.rb
Rails.application.routes.draw do

  resources :tipo_contenidos

  get 'home/index'
  get 'home/contacto'

  resources :entrada_blogs do
      resources :comentarios
  end

  resources :usuarios

   root :to => 'home#index'

  get 'foto' => 'entrada_blogs#foto'
  get 'mates' => 'entrada_blogs#mates'
  get 'editablog' => 'entrada_blogs#editablog'

resources :sitemaps, :only => :index
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

end

app/models/entrada_blog.rb
class EntradaBlog < ActiveRecord::Base

	has_many :comentarios, dependent: :destroy

	has_one :tipo_contenido
	accepts_nested_attributes_for :tipo_contenido

	validates :titulo, :body, presence: true

	#has_attached_file :image, styles: { large: '900'    ,medium: '200x200>', thumb: '48x48>' }
	
	#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/entrada_blogs_controller.rb
class EntradaBlogsController < ApplicationController
  before_action :set_entrada_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :foto, :mates, :show]


#comento el layout, porque ahora uso un ocn el mismo nombre del controlador.
#layout 'generic_layout'



  # GET /entrada_blogs
  # GET /entrada_blogs.json

   def index
    @entrada_blogs = EntradaBlog.all
  end

  def editablog
    @entrada_blogs = EntradaBlog.all 
  end

  def foto
        @entrada_blogs = EntradaBlog.find_by_sql("select entrada_blogs.* from entrada_blogs inner join tipo_contenidos
    ON entrada_blogs.id=tipo_contenidos.entrada_blog_id and tipo_contenidos.astrofoto = 't'")
  end
  def mates
    @entrada_blogs = EntradaBlog.find_by_sql("select entrada_blogs.* from entrada_blogs inner join tipo_contenidos
    ON entrada_blogs.id=tipo_contenidos.entrada_blog_id and tipo_contenidos.metematica = 't'")
  end



  # GET /entrada_blogs/1
  # GET /entrada_blogs/1.json
  def show
  end

  # GET /entrada_blogs/new
  def new
    @entrada_blog = EntradaBlog.new
    @entrada_blog.build_tipo_contenido
  end

  # GET /entrada_blogs/1/edit
  def edit
  end

  # POST /entrada_blogs
  # POST /entrada_blogs.json
  def create
    @entrada_blog = EntradaBlog.new(entrada_blog_params)


  


    respond_to do |format|
      if @entrada_blog.save

          @tipoentrada = TipoContenido.find_by_entrada_blog_id( @entrada_blog.id)

          # Seleccionamos los usuarios a los que hay que enviar el correo electrónico
          #dependiendo de sus suscripciones.

          if @tipoentrada.metematica
            @usuarios = Usuario.where({codigo: ["todo", "mates"]})
          elsif @tipoentrada.astrofoto
            @usuarios = Usuario.where({codigo: ["todo", "foto"]})
          else 
            @usuario = Usuario.all
          end


            @usuarios.each do |usuario| 
                 @usuario_correo = usuario
                 Actualizacion.notificacion(@entrada_blog, @usuario_correo).deliver_now
            end

        format.html { redirect_to @entrada_blog, notice: 'Entrada blog was successfully created.' }
        format.json { render :show, status: :created, location: @entrada_blog }
      else
        format.html { render :new }
        format.json { render json: @entrada_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrada_blogs/1
  # PATCH/PUT /entrada_blogs/1.json
  def update
    respond_to do |format|
      if @entrada_blog.update(entrada_blog_params)
        format.html { redirect_to @entrada_blog, notice: 'Entrada blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @entrada_blog }
      else
        format.html { render :edit }
        format.json { render json: @entrada_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrada_blogs/1
  # DELETE /entrada_blogs/1.json
  def destroy
    @entrada_blog.destroy
    respond_to do |format|
      format.html { redirect_to entrada_blogs_url, notice: 'Entrada blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada_blog
      @entrada_blog = EntradaBlog.find(params[:id])

      @entrada_blogs_all = EntradaBlog.all

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_blog_params
      params.require(:entrada_blog).permit(:titulo, :body, :otro1, :otro2, :image, tipo_contenido_attributes: [:astrofoto, :metematica])
      #params.require(:entrada_blog).permit(:titulo, :body, :imagen, :otro1, :otro2, :image, tipo_contenido_attributes: [:astrofoto, :metematica])

    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
      name == ENV["superuser_name"] && password == ENV["superuser_pass"]
      #ruta nuevo post: /entrada_blog/new
      #ruta editar post: /entrada_blog/5/edit
      #ruta resumen : /editablog
    end
  end
end

app/helpers/entrada_blogs_helper.rb
module EntradaBlogsHelper
end

app/views/entrada_blogs/_form.html.erb
<%= form_for(@entrada_blog) do |f| %>
  <% if @entrada_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrada_blog.errors.count, "error") %> prohibited this entrada_blog from being saved:</h2>

      <ul>
      <% @entrada_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br>
    <%= f.text_field :imagen %>
  </div>
  <div class="field">
    <%= f.label :otro1 %><br>
    <%= f.text_area :otro1 %>
  </div>
  <div class="field">
    <%= f.label :otro2 %><br>
    <%= f.text_area :otro2 %>
  </div>

 

  <%= f.fields_for :tipo_contenido do | tipo_contenido_fields | %>
    <div class="tipo_contenidos_fields">

      <div class="fields">
        <%= tipo_contenido_fields.label :astrofoto, "astrofotos" %><br>
        <%= tipo_contenido_fields.check_box :astrofoto %>
      </div>
      <div class="fields">
          <%= tipo_contenido_fields.label :metematica, "matematicas" %><br>
          <%= tipo_contenido_fields.check_box :metematica %>
      </div>

    </div>
    <% end %>

  
  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

app/views/entrada_blogs/edit.html.erb
<h1>Editing Entrada Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrada_blog %> |
<%= link_to 'Back', entrada_blogs_path %>

app/views/entrada_blogs/editablog.html.erb
<h1>Historial de entradas en el blog</h1>

<table class="table">


  <tbody>
    <% @entrada_blogs.each do |entrada_blog| %>
      <tr>

        <td><%= link_to entrada_blog.titulo, entrada_blog %></td>
        <td><%= link_to 'Edit', edit_entrada_blog_path(entrada_blog) %></td>
        <td><%= link_to 'Destroy', entrada_blog, method: :delete, data: { confirm: 'Are you sure?' } %>   </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/entrada_blogs/foto.html.erb
<h1>Historial de entradas en el blog</h1>

<table class="table">


  <tbody>
    <% @entrada_blogs.each do |entrada_blog| %>
      <tr>

        <% ruta ="/imagenes/Posts/#{entrada_blog.id}/#{entrada_blog.id}_60x40.jpg" %>
        <td> <%= link_to image_tag(ruta, :alt => "miniatura"), entrada_blog %> </td>
        <td><%= link_to entrada_blog.titulo, entrada_blog %></td>

      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/entrada_blogs/index.html.erb
<h1>Historial de entradas en el blog</h1>

<table class="table">


  <tbody>
    <% @entrada_blogs.each do |entrada_blog| %>
      <tr>

        <% ruta ="/imagenes/Posts/#{entrada_blog.id}/#{entrada_blog.id}_60x40.jpg" %>
        <td> <%= link_to image_tag(ruta, :alt => "miniatura"), entrada_blog %> </td>
        <td><%= link_to entrada_blog.titulo, entrada_blog %></td>

      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/entrada_blogs/mates.erb
<h1>Historial de entradas en el blog</h1>

<table class="table">


  <tbody>
    <% @entrada_blogs.each do |entrada_blog| %>
      <tr>
        <% ruta ="/imagenes/Posts/#{entrada_blog.id}/#{entrada_blog.id}_60x40.jpg" %>
        <td> <%= link_to image_tag(ruta, :alt => "miniatura"), entrada_blog %> </td>
        <td><%= link_to entrada_blog.titulo, entrada_blog %></td>

      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/entrada_blogs/new.html.erb
<h1>New Entrada Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', entrada_blogs_path %>

app/views/entrada_blogs/show.html.erb
<div class="cuerpo_post">


  <div id="titulo_entrada">

      <h2>
      <p>
      <%= @entrada_blog.titulo %>
      </p>
      </h2>
  
  </div>

  <div id="fecha">

      <% t_create=@entrada_blog.created_at %>
      <% t_update=@entrada_blog.updated_at %>
     Creado el día <%=  t_create.strftime("%d-%m-%Y a las %H:%M") %>.<br>
      Última actualización <%=  t_create.strftime("%d-%m-%Y a las %H:%M") %>

 
  </div>



  <div class="cuerpo_entrada">

    <p>
      <% @code =  "<p> #{@entrada_blog.body} <p>" %> 
  
      <%= @code.html_safe %>

    </p>
  </div>


    <h2> Comentarios</h2>
    
    <div id="comentarios">
      <% @entrada_blog.comentarios.each do |comentario| %>
      <%= div_for comentario do %>
      <p>
        <h4><%= h(comentario.alias) %>:</h4>
        <%= h(comentario.body) %> 
        <br>
        <h6>    Comentario escrito hace <%= time_ago_in_words(comentario.created_at) %> </h6>
        <br>
      </p>
      <% end %>
      <% end %>
    </div>

     <%= form_for([@entrada_blog, Comentario.new]) do |f| %>
         <p><%= f.label :alias, "¿Quién eres?" %><br />
           <%= f.text_field :alias %>
        </p>
        <p><%= f.label :body, "Escribe tu comentario" %><br />
           <%= f.text_area :body, :size=> "60x8" %>
        </p>
        <p><%= f.submit "Subir comentario" %></p>
    <% end %>




      <%= link_to 'Volver', entrada_blogs_path %>







        <h3>Historial de entradas en el blog</h3>

        <table class="table">


          <tbody>
            <% @entrada_blogs_all.order(id: :desc).each do |entrada_blog_all| %>
              <tr>
                <% ruta ="/imagenes/Posts/#{entrada_blog_all.id}/#{entrada_blog_all.id}_60x40.jpg" %>
                <td> <%= link_to image_tag(ruta, :alt => "miniatura"), entrada_blog_all %> </td>
                <td><%= link_to entrada_blog_all.titulo, entrada_blog_all %></td>

              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

</div>