config/routes.rb
Rails.application.routes.draw do

  resources :tipo_contenidos

  get 'home/index'
  get 'home/contacto'

  resources :entrada_blogs do
      resources :comentarios
  end

  resources :usuarios

   root :to => 'home#index'

  get 'foto' => 'entrada_blogs#foto'
  get 'mates' => 'entrada_blogs#mates'
  get 'editablog' => 'entrada_blogs#editablog'

resources :sitemaps, :only => :index
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pocas Luces</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

	<div class="logo">
		    <IMG SRC="/pocas_luces.png" ALT="Rezagadas el blog de Astronomía" width=95% >
		</div>


	<div class="col-md-3">

	     <nav class="bs-sidebar hidden-print affix-top" role="complementary">
			
	     	<ul class="nav bs-sidenav">
	     		<li><%= link_to 'Inicio', root_path %></li>
			    <li><%= link_to 'Contenidos', entrada_blogs_path %></li>
			    <li><%= link_to 'Fotografías', foto_path  %></li>
			    <li><%= link_to 'Matemáticas y Astronomía', mates_path %></li>
			    <li><%= link_to 'Contacto',home_contacto_path %></li>
			</ul>
		</nav>


		<div class="col-suscrip">
			<p id="notice"><%= notice %></p>
			<h3> Suscribirme por correo</h3>

			<%= form_for Usuario.new do |f| %>

				<div class="field">
				  <%= f.label :Nombre %>:
				  <%= f.text_field :Nombre, :size => 10 %>
				</div>
				<div class="field">
					<%= f.label :email %>:
					<%= f.text_field :email, :size => 10 %>
				</div>
				<div class="button">
					<%= f.radio_button :codigo, "foto" %>
					<%= f.label :codigo, 'Solo Fotografías' %>
				</div>
				<div class="button">
					<%= f.radio_button :codigo, "mates" %>
					<%= f.label :codigo, 'Solo matemáticas' %>
				</div>
				<div class="button">
					<%= f.radio_button :codigo, "todo", checked: true %>
					<%= f.label :codigo, 'Todas las actualizaciones' %>
				</div>


					  <%= f.simple_captcha :label => "Copia los caracteres anteriores" %>


				<div class="actions">
					<%= f.submit "Crear suscripción" %>
				</div>
			<% end %>
			



		</div>	

	</div>



	<div class="col-md-9" role="main">


	<%= yield %>

	</div>

<br>
</body>



</html>

app/views/layouts/entrada_blog.html.erb
<body>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

	<div id="cabecera">


		<div id="logo">
		    <IMG SRC="/pocas_luces.png" ALT="Rezagadas el blog de Astronomía" width=100% >
		</div>



	</div>


<br>


	<div id="menu">

		<%= render 'menu' %>

	</div>



	<div class="principal">

	<%= yield %>

	</div>

<br>
</body>

app/views/layouts/generic_layout.html.erb
<body>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>



	<div id="logo">
	    <IMG SRC="/rezagadas_logo.png" ALT="Rezagadas el blog de Astronomía" WIDTH=100%  >
	</div>
	
<br>




	</div id="menuizquierda">

	kkkkkggggggggggg gggggggggggggggggggggg gggggggggggggggggggggggg ggggggggggggggggggggggg hhhhhhhhhhhhhhhhh hhhhhhhhhhhhhhhhhhhhh hhhhhhhhhhhhhhhhhhhhhhh hhhhhhhhhhhhhhhhhhhhhhhh hhhhhhhhhhhhhhhh hhhhhhhhhhhhhhhhhh

	</div>



	</div id="principal">

	<%= yield %>

	</div>


</body>